version: '2'

services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dataVolumes/traefik/traefik.toml:/traefik.toml
      - /dataVolumes/traefik/acme:/acme
      - /dataVolumes/traefik/logs:/logs
    networks:
      - traefik_default

  p418webui:
    image: earthcube/p418webui:latest
    labels:
      - "traefik.backend=p418webui"
      - "traefik.frontend.rule=Host:geodex.org"
    volumes:
      - /dataVolumes/indexes:/indexes
    networks:
      - traefik_default

  s3system:
    image: minio/minio:latest
    labels:
      - "traefik.backend=s3system"
      - "traefik.frontend.rule=Host:geodex.org;PathPrefix:/minio"
      - "traefik.port=9000"
    volumes:
      - /dataVolumes/s3:/data
    environment:
      - MINIO_ACCESS_KEY=YUUUWSRXEXACIGAWNPKJ
      - MINIO_SECRET_KEY=AJFZEOXAQEELRCGFIJZS
    networks:
      - traefik_default
    command: ["server", "/data"]

# EarthCube CDF Registry Working Group containers

  rwgsparql:
    image: earthcube/cdfrwgrdf:latest
    labels:
      - "traefik.backend=rwgsparql"
      - "traefik.port=9999" # force to pick 9999 ignore the 8080 admin port
      - "traefik.frontend.rule=Host:repograph.net;Method:GET,POST;PathPrefix:/blazegraph"
    networks:
      - traefik_default

  rwgweb:
    image: earthcube/cdfrwgweb:latest
    labels:
      - "traefik.backend=rwgweb"
      - "traefik.frontend.rule=Host:repograph.net"
    networks:
      - traefik_default

  p418vocab:
    image: earthcube/p418vocab:latest
    labels:
      - "traefik.backend=p418vocab"
      - "traefik.frontend.rule=Host:geodex.org;PathPrefix:/voc"
      - "traefik.port=9900"
    networks:
      - traefik_default

networks:
  traefik_default: